import 'package:intl/intl.dart';

class AppLocalizations {
  final String code;

  AppLocalizations(this.code);

  static const Map<String, Map<String, String>> _strings = {
    'vi': {
      'app_name': 'Amordaily',
      'tab_home': 'Đếm ngày',
      'tab_anniversary': 'Kỷ niệm',
      'tab_settings': 'Cài đặt',
      'days_together': 'NGÀY BÊN NHAU',
      'our_love_story': 'CHUYỆN TÌNH CỦA CHÚNG TA',
      'upcoming_anniversary': 'Kỷ niệm sắp tới',
      'months_left': 'tháng',
      'days_left': 'Còn',
      'days_unit': 'ngày',
      'years': 'năm',
      'months': 'tháng',
      'days': 'ngày',
      'settings_title': 'Cài đặt',
      'your_profile': 'Hồ sơ của bạn',
      'partner_profile': 'Hồ sơ người ấy',
      'your_name': 'Tên của bạn',
      'partner_name': 'Tên người ấy',
      'your_birthday': 'Ngày sinh của bạn',
      'partner_birthday': 'Ngày sinh người ấy',
      'your_photo': 'Ảnh của bạn',
      'partner_photo': 'Ảnh người ấy',
      'love_story': 'Chuyện tình chúng mình',
      'love_start_date': 'Ngày bắt đầu yêu',
      'display': 'Hiển thị',
      'show_age': 'Hiển thị tuổi',
      'show_zodiac': 'Hiển thị cung hoàng đạo',
      'language': 'Ngôn ngữ',
      'app_info': 'Thông tin ứng dụng',
      'copyright': 'Bản quyền tác giả',
      'support': 'Liên hệ hỗ trợ',
      'cancel': 'Hủy',
      'save': 'Lưu',
      'delete': 'Xóa',
      'add': 'Thêm',
      'anniversary_title': 'Kỷ niệm của chúng mình',
      'add_anniversary': 'Thêm kỷ niệm mới',
      'anniversary_name_hint': 'Tên kỷ niệm (VD: Lần đầu gặp mặt)',
      'select_date': 'Chọn ngày',
      'delete_anniversary': 'Xóa kỷ niệm?',
      'passed': 'Đã qua',
      'not_set': 'Chưa thiết lập',
      'age': 'tuổi',
      'years_together': 'năm yêu nhau',
      'months_together': 'tháng yêu nhau',
      'days_together_milestone': 'ngày yêu nhau',
      'since': 'Từ ngày',
      'show_quotes': 'Hiển thị câu nói hay',
      'quote_1': 'Yêu không phải là nhìn nhau, mà là cùng nhìn về một hướng.',
      'quote_2': 'Nơi nào có tình yêu, nơi đó có sự sống.',
      'quote_3': 'Chỉ mất một giây để nói lời yêu, nhưng mất cả đời để chứng minh điều đó.',
      'quote_4': 'Em là lý do khiến anh mỉm cười mỗi ngày.',
      'quote_5': 'Hạnh phúc lớn nhất đời người là tìm được đúng người để yêu.',
      'partner_birthday_event': 'Sinh nhật người ấy',
      'your_birthday_event': 'Sinh nhật của bạn',
    },
    'en': {
      'app_name': 'Amordaily',
      'tab_home': 'Love Count',
      'tab_anniversary': 'Anniversary',
      'tab_settings': 'Settings',
      'days_together': 'DAYS TOGETHER',
      'our_love_story': 'OUR LOVE STORY',
      'upcoming_anniversary': 'Upcoming Anniversary',
      'months_left': 'months',
      'days_left': 'In',
      'days_unit': 'days',
      'years': 'years',
      'months': 'months',
      'days': 'days',
      'settings_title': 'Settings',
      'your_profile': 'Your Profile',
      'partner_profile': 'Partner Profile',
      'your_name': 'Your Name',
      'partner_name': 'Partner Name',
      'your_birthday': 'Your Birthday',
      'partner_birthday': 'Partner Birthday',
      'your_photo': 'Your Photo',
      'partner_photo': 'Partner Photo',
      'love_story': 'Our Love Story',
      'love_start_date': 'Love Start Date',
      'display': 'Display',
      'show_age': 'Show Age',
      'show_zodiac': 'Show Zodiac Sign',
      'language': 'Language',
      'app_info': 'App Info',
      'copyright': 'Copyright',
      'support': 'Contact Support',
      'cancel': 'Cancel',
      'save': 'Save',
      'delete': 'Delete',
      'add': 'Add',
      'anniversary_title': 'Our Anniversaries',
      'add_anniversary': 'Add New Anniversary',
      'anniversary_name_hint': 'Name (e.g. First Date)',
      'select_date': 'Select Date',
      'delete_anniversary': 'Delete Anniversary?',
      'passed': 'Passed',
      'not_set': 'Not set',
      'age': 'years old',
      'years_together': 'years together',
      'months_together': 'months together',
      'days_together_milestone': 'days together',
      'since': 'Since',
      'show_quotes': 'Show Love Quotes',
      'quote_1': 'Love is not looking at each other, but looking together in the same direction.',
      'quote_2': 'Where there is love, there is life.',
      'quote_3': 'It takes a second to say I love you, but a lifetime to prove it.',
      'quote_4': 'You are the reason I smile every day.',
      'quote_5': 'The greatest happiness in life is to find the right person to love.',
      'partner_birthday_event': 'Partner\'s Birthday',
      'your_birthday_event': 'Your Birthday',
    },
    'ja': {
      'app_name': 'Amordaily',
      'tab_home': '愛の日数',
      'tab_anniversary': '記念日',
      'tab_settings': '設定',
      'days_together': '一緒にいる日々',
      'our_love_story': '私たちの愛の物語',
      'upcoming_anniversary': 'もうすぐ記念日',
      'days_left': 'あと',
      'days_unit': '日',
      'years': '年',
      'months': 'ヶ月',
      'days': '日',
      'settings_title': '設定',
      'your_profile': 'あなたのプロフィール',
      'partner_profile': '相手のプロフィール',
      'your_name': 'あなたの名前',
      'partner_name': '相手の名前',
      'your_birthday': 'あなたの誕生日',
      'partner_birthday': '相手の誕生日',
      'your_photo': 'あなたの写真',
      'partner_photo': '相手の写真',
      'love_story': '愛の始まり',
      'love_start_date': '付き合い始めた日',
      'display': '表示設定',
      'show_age': '年齢を表示',
      'show_zodiac': '星座を表示',
      'language': '言語',
      'app_info': 'アプリ情報',
      'copyright': '著作権',
      'support': 'サポートに連絡',
      'cancel': 'キャンセル',
      'save': '保存',
      'delete': '削除',
      'add': '追加',
      'anniversary_title': '私たちの記念日',
      'add_anniversary': '新しい記念日を追加',
      'anniversary_name_hint': '記念日の名前（例：初デート）',
      'select_date': '日付を選択',
      'delete_anniversary': '記念日を削除しますか？',
      'passed': '過去',
      'not_set': '未設定',
      'age': '歳',
      'years_together': '周年',
      'months_together': 'ヶ月記念',
      'days_together_milestone': '日記念',
      'since': '開始日',
      'show_quotes': '愛の名言を表示',
      'quote_1': '愛とはお互いを見つめ合うことではなく、共に同じ方向を見つめることである。',
      'quote_2': '愛のあるところに、生がある。',
      'quote_3': '「愛してる」と言うのは一瞬だが、それを証明するには一生かかる。',
      'quote_4': 'あなたは私が毎日笑顔でいられる理由です。',
      'quote_5': '人生最大の幸福は、愛すべき人を見つけることだ。',
      'partner_birthday_event': '相手の誕生日',
      'your_birthday_event': 'あなたの誕生日',
    },
    'ko': {
      'app_name': 'Amordaily',
      'tab_home': '디데이',
      'tab_anniversary': '기념일',
      'tab_settings': '설정',
      'days_together': '함께한 날',
      'our_love_story': '우리의 러브스토리',
      'upcoming_anniversary': '다가오는 기념일',
      'days_left': '남은',
      'days_unit': '일',
      'years': '년',
      'months': '개월',
      'days': '일',
      'settings_title': '설정',
      'your_profile': '내 프로필',
      'partner_profile': '상대방 프로필',
      'your_name': '내 이름',
      'partner_name': '상대방 이름',
      'your_birthday': '내 생일',
      'partner_birthday': '상대방 생일',
      'your_photo': '내 사진',
      'partner_photo': '상대방 사진',
      'love_story': '우리의 시작',
      'love_start_date': '사귀기 시작한 날',
      'display': '표시 설정',
      'show_age': '나이 표시',
      'show_zodiac': '별자리 표시',
      'language': '언어',
      'app_info': '앱 정보',
      'copyright': '저작권',
      'support': '지원 문의',
      'cancel': '취소',
      'save': '저장',
      'delete': '삭제',
      'add': '추가',
      'anniversary_title': '우리의 기념일',
      'add_anniversary': '새 기념일 추가',
      'anniversary_name_hint': '기념일 이름 (예: 첫 만남)',
      'select_date': '날짜 선택',
      'delete_anniversary': '기념일을 삭제할까요?',
      'passed': '지남',
      'not_set': '미설정',
      'age': '살',
      'years_together': '주년',
      'months_together': '개월 기념',
      'days_together_milestone': '일 기념',
      'since': '시작일',
      'show_quotes': '사랑의 명언 표시',
      'quote_1': '사랑은 서로를 바라보는 것이 아니라, 같은 방향을 함께 바라보는 것이다.',
      'quote_2': '사랑이 있는 곳에 삶이 있다.',
      'quote_3': '사랑한다는 말을 하는 데는 1초가 걸리지만, 그것을 증명하는 데는 평생이 걸린다.',
      'quote_4': '당신은 내가 매일 웃는 이유입니다.',
      'quote_5': '인생 최고의 행복은 사랑할 사람을 찾는 것이다.',
      'partner_birthday_event': '상대방 생일',
      'your_birthday_event': '내 생일',
    },
    'zh': {
      'app_name': 'Amordaily',
      'tab_home': '恋爱天数',
      'tab_anniversary': '纪念日',
      'tab_settings': '设置',
      'days_together': '在一起的日子',
      'our_love_story': '我们的爱情故事',
      'upcoming_anniversary': '即将到来的纪念日',
      'days_left': '还有',
      'days_unit': '天',
      'years': '年',
      'months': '个月',
      'days': '天',
      'settings_title': '设置',
      'your_profile': '我的资料',
      'partner_profile': '对方资料',
      'your_name': '我的名字',
      'partner_name': '对方名字',
      'your_birthday': '我的生日',
      'partner_birthday': '对方生日',
      'your_photo': '我的照片',
      'partner_photo': '对方照片',
      'love_story': '爱情的开始',
      'love_start_date': '恋爱开始日',
      'display': '显示设置',
      'show_age': '显示年龄',
      'show_zodiac': '显示星座',
      'language': '语言',
      'app_info': '应用信息',
      'copyright': '版权',
      'support': '联系支持',
      'cancel': '取消',
      'save': '保存',
      'delete': '删除',
      'add': '添加',
      'anniversary_title': '我们的纪念日',
      'add_anniversary': '添加新纪念日',
      'anniversary_name_hint': '纪念日名称（如：初次相遇）',
      'select_date': '选择日期',
      'delete_anniversary': '删除纪念日？',
      'passed': '已过',
      'not_set': '未设置',
      'age': '岁',
      'years_together': '周年',
      'months_together': '个月纪念',
      'days_together_milestone': '天纪念',
      'since': '开始日期',
      'show_quotes': '显示爱情金句',
      'quote_1': '爱不是寻找一个完美的人，而是学会用完美的眼光去欣赏一个不完美的人。',
      'quote_2': '哪里有爱，哪里就有生命。',
      'quote_3': '说我爱你只需要一秒钟，但证明它需要一辈子。',
      'quote_4': '你是我每天微笑的原因。',
      'quote_5': '人生最大的幸福是发现值得去爱的人。',
      'partner_birthday_event': '对方生日',
      'your_birthday_event': '我的生日',
    },
    'ru': {
      'app_name': 'Amordaily',
      'tab_home': 'Счётчик',
      'tab_anniversary': 'Годовщины',
      'tab_settings': 'Настройки',
      'days_together': 'ДНЕЙ ВМЕСТЕ',
      'our_love_story': 'НАША ИСТОРИЯ ЛЮБВИ',
      'upcoming_anniversary': 'Ближайшая годовщина',
      'days_left': 'Через',
      'days_unit': 'дн.',
      'years': 'г.',
      'months': 'мес.',
      'days': 'дн.',
      'settings_title': 'Настройки',
      'your_profile': 'Мой профиль',
      'partner_profile': 'Профиль партнёра',
      'your_name': 'Моё имя',
      'partner_name': 'Имя партнёра',
      'your_birthday': 'Мой день рождения',
      'partner_birthday': 'День рождения партнёра',
      'your_photo': 'Моё фото',
      'partner_photo': 'Фото партнёра',
      'love_story': 'Наша история',
      'love_start_date': 'Начало отношений',
      'display': 'Отображение',
      'show_age': 'Показывать возраст',
      'show_zodiac': 'Показывать знак зодиака',
      'language': 'Язык',
      'app_info': 'Об приложении',
      'copyright': 'Авторские права',
      'support': 'Связаться с поддержкой',
      'cancel': 'Отмена',
      'save': 'Сохранить',
      'delete': 'Удалить',
      'add': 'Добавить',
      'anniversary_title': 'Наши годовщины',
      'add_anniversary': 'Добавить годовщину',
      'anniversary_name_hint': 'Название (например: Первое свидание)',
      'select_date': 'Выбрать дату',
      'delete_anniversary': 'Удалить годовщину?',
      'passed': 'Прошло',
      'not_set': 'Не задано',
      'age': 'лет',
      'years_together': 'лет вместе',
      'months_together': 'мес. вместе',
      'days_together_milestone': 'дней вместе',
      'since': 'С',
      'show_quotes': 'Показывать цитаты о любви',
      'quote_1': 'Любить — это не значит смотреть друг на друга, а смотреть в одном направлении.',
      'quote_2': 'Там, где есть любовь, есть жизнь.',
      'quote_3': 'Чтобы сказать «я люблю тебя», нужна секунда, а чтобы доказать это — вся жизнь.',
      'quote_4': 'Ты — причина моей улыбки каждый день.',
      'quote_5': 'Величайшее счастье в жизни — найти человека, которого стоит любить.',
      'partner_birthday_event': 'День рождения партнёра',
      'your_birthday_event': 'Мой день рождения',
    },
  };

  static const Map<String, String> languageNames = {
    'en': '🇬🇧 English',
    'vi': '🇻🇳 Tiếng Việt',
    'ru': '🇷🇺 Русский',
    'ja': '🇯🇵 日本語',
    'ko': '🇰🇷 한국어',
    'zh': '🇨🇳 中文',
  };

  static const List<String> supportedCodes = ['en', 'vi', 'ru', 'ja', 'ko', 'zh'];

  String t(String key) {
    return _strings[code]?[key] ?? _strings['en']?[key] ?? key;
  }

  static String formatDate(DateTime date, String langCode) {
    if (langCode == 'vi') {
      return DateFormat('dd/MM/yyyy').format(date);
    } else if (langCode == 'en') {
      return DateFormat('MM/dd/yyyy').format(date);
    }
    return DateFormat('dd/MM/yyyy').format(date);
  }
}
