import 'dart:math';

class QuotesData {
  static final Map<String, List<String>> _allQuotes = {
    'vi': [
      "Yêu không chỉ là một danh từ - nó là một động từ; nó không chỉ là cảm xúc - nó là sự quan tâm, chia sẻ, giúp đỡ, hy sinh.",
      "Tình yêu lớn không phải là yêu nhiều người mà là yêu một người và suốt đời.",
      "Hạnh phúc không phải là có tất cả những gì bạn muốn, mà là trân trọng những gì bạn đang có.",
      "Yêu là khi bạn thấy ở người đó những điều không hoàn hảo nhưng vẫn yêu họ một cách hoàn hảo.",
      "Tình yêu biến những điều bình thường thành những điều phi thường.",
      "Gặp gỡ là duyên phận, ở bên nhau là lựa chọn.",
      "Em là mảnh ghép hoàn hảo nhất của cuộc đời anh.",
      "Chỉ cần có em bên cạnh, thế giới của anh luôn rực rỡ.",
      "Cảm ơn em đã xuất hiện và làm cho cuộc đời anh ý nghĩa hơn.",
      "Anh muốn cùng em già đi, và đếm từng ngày chúng ta bên nhau.",
      "Tình yêu không phải là tìm thấy một ai đó hoàn hảo để ở bên cạnh, mà là học cách nhìn thấy những điều hoàn hảo từ một người không hoàn hảo.",
      "Có một nơi để về, đó là nhà. Có những người để yêu thương, đó là gia đình. Có được cả hai, đó là hạnh phúc.",
      "Trong thế giới của anh, em chính là định nghĩa của hạnh phúc.",
      "Yêu một người là muốn cùng người đó đi hết cuộc đời, dù là những ngày nắng hay những ngày mưa.",
      "Anh không cần một thế giới quá lớn, vì với anh, em đã là cả thế giới rồi.",
      "Hôn em là cách anh nói yêu em mà không cần dùng đến lời nói.",
      "Được yêu em là điều may mắn nhất trong cuộc đời anh.",
      "Em là lý do khiến anh tin vào những điều kỳ diệu trong cuộc sống.",
      "Em là tia nắng ấm áp nhất xua tan đi những ngày đông giá rét trong anh.",
      "Tình yêu của chúng mình giống như một bản nhạc không lời, nhẹ nhàng nhưng sâu lắng.",
      "Anh muốn là người cuối cùng em nhìn thấy trước khi ngủ và là người đầu tiên em thấy khi thức dậy.",
      "Cảm ơn em đã kiên nhẫn và yêu thương một người như anh.",
      "Thế giới này có hàng tỷ người, nhưng anh chỉ cần một mình em thôi.",
      "Yêu em là việc duy nhất anh muốn làm trong suốt quãng đời còn lại.",
      "Em là tất cả những gì anh từng mơ ước và nhiều hơn thế nữa.",
      "Dù thời gian có trôi đi, tình yêu anh dành cho em vẫn vẹn nguyên như ngày đầu.",
      "Em là người biến những ngày bình thường của anh thành những ngày lễ hội.",
      "Anh yêu cách em cười, cách em nói và cả cách em giận dỗi anh.",
      "Chỉ cần nắm tay em, anh có thể đi đến bất cứ nơi đâu.",
      "Em là món quà tuyệt vời nhất mà thượng đế đã ban tặng cho anh.",
      "Tình yêu của anh dành cho em rộng lớn như đại dương và bao la như bầu trời.",
      "Mỗi lần nhìn vào mắt em, anh thấy cả tương lai của chúng mình ở đó.",
      "Anh sẽ luôn là bờ vai vững chắc để em dựa vào mỗi khi mệt mỏi.",
      "Yêu em là hơi thở, là cuộc sống và là định mệnh của anh.",
      "Cảm ơn cuộc đời đã cho anh gặp được em giữa hàng triệu người.",
      "Em chính là mảnh ghép cuối cùng để trái tim anh trở nên hoàn chỉnh.",
      "Không có gì có thể thay thế được vị trí của em trong trái tim anh.",
      "Anh yêu em nhiều hơn cả lời nói có thể diễn tả.",
      "Cùng em đi khắp thế gian là ước nguyện lớn nhất của anh.",
      "Tình yêu chúng mình là một hành trình không có điểm kết thúc.",
      "Mỗi giây phút bên em đều là những khoảnh khắc vô giá.",
      "Anh yêu em bằng tất cả những gì anh có.",
      "Em là người duy nhất khiến anh cảm thấy mình đặc biệt.",
      "Hạnh phúc là khi được cùng em già đi mỗi ngày.",
      "Nếu khoảng cách giữa chúng ta là một nghìn bước, anh chỉ cần em bước một bước, anh sẽ bước chín trăm chín mươi chín bước còn lại.",
      "Anh không thể hứa sẽ giải quyết được hết mọi rắc rối của em, nhưng anh hứa em sẽ không phải đối mặt với chúng một mình.",
      "Tình yêu không phải là đếm bao nhiêu ngày, mà là khiến những ngày đó trở nên đáng nhớ.",
      "Trong đôi mắt em, anh tìm thấy ngôi nhà mà anh hằng mong ước.",
      "Anh yêu em không phải vì em hoàn hảo, mà vì em hoàn hảo đối với anh.",
      "Yêu một người là trao cho họ sức mạnh để làm tổn thương mình, nhưng lại tin rằng họ sẽ không làm thế.",
      "Hạnh phúc nhất là khi tìm thấy một người có thể hiểu được sự im lặng của mình.",
      "Mọi thứ rồi sẽ qua đi, chỉ có tình yêu của chúng ta là ở lại mãi mãi.",
      "Anh muốn cùng em viết tiếp những chương đẹp nhất của cuộc đời.",
      "Em là bình minh rực rỡ sau những đêm dài tăm tối.",
      "Dù đi đâu, làm gì, trái tim anh vẫn luôn hướng về phía em.",
      "Tình yêu là khi anh nhìn thấy cả thế giới trong một người.",
      "Anh cảm ơn định mệnh đã mang em đến bên đời anh.",
      "Em là giấc mơ đẹp nhất mà anh không bao giờ muốn tỉnh lại.",
      "Bên em, anh cảm thấy mình có thể làm được tất cả mọi thứ.",
      "Tình yêu của chúng ta là một món quà vô giá từ thượng đế.",
      "Anh muốn dành cả cuộc đời này để chăm sóc và yêu thương em.",
      "Em là tất cả những gì anh cần để cảm thấy cuộc sống này ý nghĩa.",
      "Hạnh phúc là khi thấy nụ cười của em mỗi ngày.",
      "Anh yêu em, hôm nay nhiều hơn hôm qua và ít hơn ngày mai.",
      "Em là hơi ấm trong mùa đông, là gió mát trong mùa hè của anh.",
      "Tình yêu là khi hai trái tim đập cùng một nhịp.",
      "Anh sẽ luôn bên em, dù cuộc đời có bao nhiêu đổi thay.",
      "Em là người duy nhất anh muốn chia sẻ mọi buồn vui trong cuộc sống.",
      "Yêu em là định mệnh, là sự lựa chọn đúng đắn nhất của anh.",
      "Anh muốn là người bảo vệ cho giấc mơ của em.",
      "Cảm ơn em đã tin tưởng và chọn anh làm người đồng hành.",
      "Tình yêu chúng ta là một điều kỳ diệu giữa cuộc sống bình thường.",
      "Anh yêu em bằng cả trái tim và linh hồn mình.",
      "Em là điều tốt đẹp nhất từng xảy ra với anh.",
      "Dù thế giới có quay lưng, anh vẫn sẽ luôn ở đây, phía sau em.",
      "Tình yêu là ngôn ngữ của trái tim, và trái tim anh chỉ gọi tên em.",
      "Anh muốn cùng em tạo nên những ký niệm đẹp nhất.",
      "Em là lý do để anh nỗ lực hơn mỗi ngày.",
      "Hạnh phúc đơn giản là được ở bên em, nghe em nói và thấy em cười.",
      "Anh yêu em, mãi mãi và một ngày.",
      "Em là ngôi sao dẫn đường cho anh trong đêm tối.",
      "Tình yêu chúng mình là một bản tình ca không bao giờ kết thúc.",
      "Anh muốn dành trọn thanh xuân và cả cuộc đời này để yêu em.",
      "Em là mảnh ghép mà anh đã tìm kiếm bấy lâu nay.",
      "Không có gì có thể làm thay đổi tình cảm của anh dành cho em.",
      "Anh yêu em hơn bất cứ điều gì trên thế gian này.",
      "Em là nguồn cảm hứng lớn nhất của đời anh.",
      "Cùng em đi qua những thăng trầm của cuộc đời là vinh hạnh của anh.",
      "Tình yêu là khi anh thấy mình tốt đẹp hơn khi có em bên cạnh.",
      "Anh hứa sẽ không bao giờ để em phải cô đơn.",
      "Em là đóa hoa rực rỡ nhất trong vườn hoa cuộc đời anh.",
      "Yêu em là điều tự nhiên nhất mà anh từng thực hiện.",
      "Anh muốn cùng em chia sẻ những điều giản dị nhất.",
      "Em là bình yên sau những ngày giông bão.",
      "Tình yêu chúng mình là một hành trình kỳ diệu.",
      "Anh yêu em từ cái nhìn đầu tiên và mãi mãi về sau.",
      "Em là cả bầu trời đầy sao trong đêm tối của anh.",
      "Anh sẽ luôn trân trọng từng phút giây chúng mình bên nhau.",
      "Em là điều tuyệt vời nhất mà anh từng có được.",
      "Tình yêu là sức mạnh giúp anh vượt qua mọi khó khăn.",
      "Anh muốn là người khiến em cảm thấy hạnh phúc nhất thế giới.",
      "Em là tất cả những gì anh mong đợi ở một người phụ nữ.",
      "Yêu em là niềm hạnh phúc lớn nhất của đời anh.",
      "Anh hứa sẽ luôn lắng nghe và thấu hiểu em.",
      "Em là người duy nhất anh muốn nắm tay đi đến cuối con đường.",
      "Tình yêu chúng ta là một món quà đặc biệt.",
      "Anh yêu em, không chỉ vì ngoại hình mà vì tâm hồn em.",
      "Em là người biến cuộc đời anh thành một thiên đường.",
      "Anh muốn cùng em xây dựng một tổ ấm đầy yêu thương.",
      "Em là lý do để anh mỉm cười mỗi khi thức dậy.",
      "Tình yêu là khi anh thấy mình cần có em hơn bao giờ hết.",
      "Anh sẽ luôn là người hâm mộ trung thành nhất của em.",
      "Em là người phụ nữ đẹp nhất trong mắt anh.",
      "Yêu em là điều đúng đắn nhất anh từng làm.",
      "Anh muốn cùng em đi đến tận cùng của thế gian.",
      "Em là báu vật vô giá mà anh sẽ luôn gìn giữ.",
      "Tình yêu chúng ta là một câu chuyện đẹp.",
      "Anh yêu em, trọn đời này và mãi mãi.",
      "Anh muốn cùng em đi qua mọi giông bão của cuộc đời.",
      "Em là điều tuyệt vời nhất mà anh có thể gọi là \"của mình\".",
      "Trái tim anh chỉ có một ngăn, và nó đã dành trọn cho em.",
      "Yêu em không phải là một sự lựa chọn, đó là định mệnh.",
      "Mỗi ngày bên em đều là một ngày hạnh phúc nhất.",
      "Anh hứa sẽ luôn trân trọng và bảo vệ tình yêu của chúng mình.",
      "Em là nguồn năng lượng tích cực nhất trong cuộc sống của anh.",
      "Chỉ cần có em, mọi khó khăn đều trở nên nhỏ bé.",
      "Anh yêu cách em nhìn anh, đầy ấm áp và tin tưởng.",
      "Tình yêu của chúng mình là một hành trình không có điểm dừng.",
      "Anh muốn là người cùng em chia sẻ mọi khoảnh khắc trong đời.",
      "Em là báu vật mà anh sẽ luôn gìn giữ trong lòng.",
      "Yêu em là điều đúng đắn nhất mà anh từng thực hiện.",
      "Anh sẽ luôn là điểm tựa vững chắc nhất cho em.",
      "Em là lý do khiến anh muốn trở thành một người tốt hơn.",
      "Hạnh phúc là khi được cùng em già đi theo năm tháng.",
      "Anh yêu em bằng cả trái tim và linh hồn mình.",
      "Em là mảnh ghép cuối cùng hoàn thiện bức tranh cuộc đời anh.",
      "Cảm ơn em đã luôn ở bên cạnh và ủng hộ anh.",
      "Tình yêu của chúng mình sẽ mãi vững bền theo thời gian.",
    ],
    'en': [
      "Love is not about how many days, months, or years you have been together. Love is about how much you love each other every single day.",
      "Being someone's first love may be great, but to be their last is beyond perfect.",
      "In your smile, I see something more beautiful than the stars.",
      "I love you for all that you are, all that you have been, and all that you are yet to be.",
      "Together is my favorite place to be.",
      "You are my today and all of my tomorrows.",
      "I saw that you were perfect, and so I loved you. Then I saw that you were not perfect and I loved you even more.",
      "To the world, you may be one person, but to one person you are the world.",
      "I'm much more me when I'm with you.",
      "My heart is and always will be yours.",
      "Life is not the amount of breaths you take, it's the moments that take your breath away.",
      "I love you more than words can show, I think about you more than you could ever know.",
      "If I know what love is, it is because of you.",
      "Home is wherever I'm with you.",
      "Your love is all I need to feel complete.",
      "I fell in love with you because of all the small things you don't even know you're doing.",
      "The best thing to hold onto in life is each other.",
      "You are the best thing that's ever been mine.",
      "Every love story is beautiful, but ours is my favorite.",
      "You stole my heart, but I'll let you keep it.",
      "I wish I could turn back the clock. I'd find you sooner and love you longer.",
      "Loving you is my greatest adventure.",
      "You are the lyrics to my song and the rhythm to my heart.",
      "The first time I saw you, my heart whispered: 'That's the one.'",
      "I don't need a perfect life, I just need you by my side.",
      "You make my heart skip a beat and my soul feel at peace.",
      "In a room full of art, I'd still stare at you.",
      "Falling in love with you was the easiest thing I've ever done.",
      "You are my sun, my moon, and all my stars.",
      "Whatever our souls are made of, yours and mine are the same.",
      "I want to be your favorite hello and your hardest goodbye.",
      "You're the coffee I need in the morning and the dream I want at night.",
      "Meeting you was fate, becoming your friend was a choice, but falling in love with you was beyond my control.",
      "If I had a flower for every time I thought of you, I could walk through my garden forever.",
      "You are my heart's greatest joy.",
      "To love and be loved is to feel the sun from both sides.",
      "My love for you is a journey, starting at forever and ending at never.",
      "You are the peace in my chaotic world.",
      "I find pieces of you in every song I listen to.",
      "Grow old along with me! The best is yet to be.",
      "You are the peanut butter to my jelly.",
      "I love you without knowing how, or when, or from where.",
      "Distance means so little when someone means so much.",
      "You are the reason I believe in love.",
      "Every day I love you more, today more than yesterday and less than tomorrow.",
      "You are my happy place.",
      "I choose you. And I'll choose you over and over and over.",
      "Without you, I am nothing. With you, I am something. Together, we are everything.",
      "You're the best part of my day.",
      "Heaven is a place on earth with you.",
      "You are the best thing I never knew I needed.",
      "Loving you was like going to war and coming back a hero.",
      "You are the heart of my home.",
      "I would rather spend one lifetime with you than face all the ages of this world alone.",
      "You're my person.",
      "You make me want to be a better man.",
      "Love is like the wind, you can't see it but you can feel it.",
      "You are the poetry of my life.",
      "I love you more than pizza, and that's saying a lot.",
      "You are the sunshine in my rain.",
      "The best is yet to come.",
      "You're my end and my beginning.",
      "You had me at hello.",
      "I'm yours, no refunds.",
      "You are the only exception.",
      "Every time I see you, I fall in love all over again.",
      "You are the answer to every prayer I've offered.",
      "I can't imagine my life without you.",
      "You are the star that guides me home.",
      "My love for you grows stronger every day.",
      "You're the missing piece to my puzzle.",
      "I love you to the moon and back.",
      "You are the most beautiful person I know, inside and out.",
      "I'm so grateful to have you in my life.",
      "You are my soulmate.",
      "Loving you is the best decision I've ever made.",
      "You are my forever and always.",
      "I promise to love you through thick and thin.",
      "You are my greatest blessing.",
      "I want to spend the rest of my life making you happy.",
      "You are the light of my life.",
      "I love the way you look at me.",
      "You are my dream come true.",
      "I'm so lucky to be loved by you.",
      "You are the reason for my smile.",
      "I love you more than I can say.",
      "You are my world.",
      "I can't wait to grow old with you.",
      "You are my everything.",
      "I love you more than all the stars in the sky.",
      "You are my ultimate goal.",
      "I'm yours forever.",
      "You are the best gift life has given me.",
      "I love you with all my heart.",
      "You are my sunshine on a cloudy day.",
      "I'll love you until the end of time.",
      "You are the music in my soul.",
      "I'm so proud to be your partner.",
      "You are my one and only.",
      "I love you more than life itself.",
      "You are the reason I wake up with a smile every morning.",
      "My love for you is beyond anything I could ever express.",
      "Every moment spent with you is a treasure I cherish forever.",
      "You make my life complete in ways I never thought possible.",
      "I promise to be your rock and your safe haven always.",
      "You are the most precious gift I have ever received.",
      "Loving you is the easiest and most natural thing in the world.",
      "I want to build a future filled with love and laughter with you.",
      "Your happiness is my priority, today and every day.",
      "You are the one my heart has been searching for all along.",
      "I am so lucky to call you mine and walk through life with you.",
      "Your love gives me the strength to face any challenge.",
      "I cherish the deep connection we share, heart to heart.",
      "You are my partner, my confidant, and my best friend.",
      "I love the way you make every ordinary day feel extraordinary.",
      "My heart belongs to you, now and for all eternity.",
      "You are the light that guides me through the darkest times.",
      "I am constantly amazed by your beauty, both inside and out.",
      "Being with you feels like coming home to where I belong.",
      "Our love is a beautiful journey that I never want to end.",
    ],
    'ja': [
      "愛とは、お互いを見つめ合うことではなく、共に同じ方向を見つめることである。",
      "君の笑顔は、星よりも美しい。",
      "あなたに出会えて、本当によかった。",
      "ずっと、あなたのそばにいたいです。",
      "世界で一番、あなたが大切です。",
      "君がいるから、毎日が輝いている。",
      "愛してる。言葉では足りないくらい。",
      "あなたは私の運命の人です。",
      "一緒にいるだけで、幸せを感じる。",
      "これからも、ずっと隣にいてね。",
      "君は僕の宝物だよ。",
      "何があっても、君を守り抜く。",
      "あなたの声を聞くだけで、心が落ち着く。",
      "君と出会った日から、世界が変わった。",
      "一瞬一瞬が、君との大切な思い出。",
      "愛とは、相手の幸せを願うこと。",
      "君が笑えば、僕も幸せになれる。",
      "あなたの優しさに、いつも救われています。",
      "この広い世界で、君を見つけられてよかった。",
      "二人の未来を、一緒に歩んでいこう。",
      "君のことが、誰よりも好きです。",
      "あなたのすべてを、愛しています。",
      "出会いは偶然、恋は必然。",
      "君は僕の心の支えだよ。",
      "明日も、その先も、君と一緒にいたい。",
      "言葉にしなくても、伝わる愛がある。",
      "君の手を、ずっと離したくない。",
      "あなたの笑顔が、私の元気の源です。",
      "どんな困難も、二人なら乗り越えられる。",
      "君という存在が、僕の誇りだよ。",
      "愛している。それ以上の言葉が見つからない。",
      "あなたと過ごす時間は、私の一生の宝物。",
      "世界でたった一人の、大切な君へ。",
      "君の幸せが、僕の幸せだよ。",
      "いつも、ありがとう。愛してる。",
      "これからも、変わらぬ愛を君に。",
      "あなたの横顔を見ているだけで、胸がいっぱいになる。",
      "君は、僕にとっての天使だよ。",
      "一生、君を離さない。",
      "出会えた奇跡に、感謝しています。",
      "あなたの瞳の中に、私の未来が見える。",
      "愛は、育むもの。二人で大切にしていこう。",
      "君がいれば、それだけでいい。",
      "ずっと、恋人でいてください。",
      "愛の力で、世界を輝かせよう。",
      "君の温もりが、僕を包み込む。",
      "あなたは、私の太陽のような存在です。",
      "二人で紡ぐ、愛の物語。",
      "君を愛すること、それが僕の使命。",
      "永遠に、君だけを愛し続ける。",
      "あなたと一緒にいると、時間が経つのを忘れてしまいます。",
      "君の幸せが、僕にとって一番の喜びだよ。",
      "これからもずっと、二人で手をつないで歩いていこう。",
      "あなたは私の人生に欠かせない、大切な存在です。",
      "君の優しい笑顔に、いつも癒されています。",
      "どんな時も、君の味方でいたい。",
      "あなたと出会えたことは、神様からの贈り物です。",
      "二人の絆は、何があっても壊れることはない。",
      "君を愛しているという気持ちは、永遠に変わらない。",
      "あなたのそばにいるだけで、心が温かくなります。",
      "これからも一緒に、たくさんの思い出を作っていこう。",
      "君は僕にとって、世界でたった一人の特別な人。",
      "あなたの夢を、一番近くで応援させてください。",
      "二人の未来が、輝かしいものでありますように。",
      "君と過ごす毎日は、宝物のような時間です。",
      "あなたの優しさが、私の心をいつも満たしてくれます。",
      "どんなに離れていても、心はいつも君のそばにある。",
      "君は僕の人生を彩ってくれる、最高のパートナー。",
      "あなたと一緒に年を重ねていくことが、私の願いです。",
      "愛してる。君のすべてを、心から。",
    ],
    'ko': [
      "사랑은 마주 보는 것이 아니라 함께 같은 방향을 보는 것이다.",
      "너의 미소는 별보다 아름다워.",
      "당신을 만난 건 내 생애 최고의 행운입니다.",
      "영원히 당신 곁에 머물고 싶어요.",
      "세상에서 당신이 가장 소중합니다.",
      "네가 있어서 매일이 눈부시게 빛나.",
      "사랑해. 말로 다 표현할 수 없을 만큼.",
      "당신은 나의 운명입니다.",
      "함께 있는 것만으로도 행복해.",
      "앞으로도 쭉 내 곁에 있어줘.",
      "너는 나의 보물이야.",
      "무슨 일이 있어도 널 지켜줄게.",
      "당신의 목소리만 들어도 마음이 편안해져요.",
      "너를 만난 날부터 세상이 달라졌어.",
      "한순간 한순간이 너와의 소중한 추억이야.",
      "사랑이란 상대방의 행복을 바라는 것.",
      "네가 웃으면 나도 행복해져.",
      "당신의 다정함에 항상 고마워요.",
      "이 넓은 세상에서 널 만날 수 있어서 다행이야.",
      "우리의 미래를 함께 걸어가자.",
      "누구보다 너를 좋아해.",
      "당신의 모든 것을 사랑합니다.",
      "만남은 우연이지만 사랑은 필연이야.",
      "너는 내 마음의 버팀목이야.",
      "내일도, 그 다음 날도 너와 함께하고 싶어.",
      "말하지 않아도 전해지는 사랑이 있어.",
      "네 손을 영원히 놓지 않을게.",
      "당신의 미소가 나의 힘의 원천이에요.",
      "어떤 어려움도 우리 둘이라면 이겨낼 수 있어.",
      "너라는 존재가 나의 자랑이야.",
      "사랑해. 그 이상의 말을 찾을 수 없어.",
      "당신과 보내는 시간은 내 평생의 보물이야.",
      "세상에 단 하나뿐인 소중한 너에게.",
      "너의 행복이 곧 나의 행복이야.",
      "항상 고마워. 그리고 사랑해.",
      "앞으로도 변치 않는 사랑을 너에게 줄게.",
      "당신의 옆모습을 보는 것만으로도 가슴이 벅차요.",
      "너는 나에게 천사 같은 존재야.",
      "평생 널 놓지 않을 거야.",
      "우리가 만난 기적에 감사해.",
      "당신의 눈동자 속에 나의 미래가 보여요.",
      "사랑은 키워나가는 것. 둘이서 소중히 간직하자.",
      "네가 있으면 그것만으로 충분해.",
      "영원히 나의 연인이 되어줘.",
      "사랑의 힘으로 세상을 밝히자.",
      "너의 온기가 나를 감싸줘.",
      "당신은 나에게 태양 같은 존재입니다.",
      "둘이서 써 내려가는 사랑 이야기.",
      "너를 사랑하는 것, 그것이 나의 사명이야.",
      "영원히 너만을 사랑할게.",
      "당신과 함께라면 그 어떤 어려움도 이겨낼 수 있어요.",
      "당신은 내 삶의 가장 아름다운 선물입니다.",
      "언제나 당신 편이 되어 줄게요.",
      "당신의 웃음소리가 세상에서 가장 듣기 좋아요.",
      "우리 함께 그려갈 미래가 너무 기대돼요.",
      "당신이라는 사람을 만난 건 기적과도 같아요.",
      "당신의 따뜻한 손길이 저에게 큰 힘이 됩니다.",
      "사랑한다는 말로도 부족한 나의 마음을 알아주세요.",
      "당신과 함께 걷는 이 길이 영원했으면 좋겠어요.",
      "세상 그 무엇보다 당신을 아끼고 사랑합니다.",
      "당신은 나를 더 좋은 사람이 되고 싶게 만들어요.",
      "힘든 일이 있을 때 언제든 내 어깨에 기대세요.",
      "당신의 존재만으로도 나의 하루는 충분히 행복합니다.",
      "우리만의 소중한 추억들을 하나씩 쌓아가요.",
      "당신은 내 마음속에 영원히 피어있을 꽃입니다.",
      "어떤 순간에도 당신을 믿고 지지할게요.",
      "당신과 함께 늙어가는 것이 나의 가장 큰 소망입니다.",
      "나의 모든 계절은 당신으로 가득 차 있어요.",
      "당신의 행복을 위해 내가 더 노력할게요.",
      "영원히 변치 않는 마음으로 당신을 사랑하겠습니다.",
    ],
    'zh': [
      "爱不是寻找一个完美的人，而是学会用完美的眼光去欣赏一个不完美的人。",
      "你的笑容比星星还要美丽。",
      "遇见你是我一生中最幸运的事。",
      "我想永远留在你身边。",
      "在这个世界上，你对我最重要。",
      "因为有你，每一天都闪闪发光。",
      "我爱你，胜过千言万语。",
      "你就是我的命中注定。",
      "只要和你在一起，我就感到幸福。",
      "以后也请一直陪在我身边。",
      "你是我的宝贝。",
      "无论发生什么，我都会守护你。",
      "听到你的声音，我的心就安定了。",
      "自从遇见你，我的世界都变了。",
      "每一分每一秒都是和你珍贵的回忆。",
      "爱是希望对方过得幸福。",
      "你笑，我也跟着幸福。",
      "谢谢你总是那么温柔地对待我。",
      "能在茫茫人海中找到你，真好。",
      "让我们一起走向未来。",
      "我比任何人都喜欢你。",
      "我爱你的全部。",
      "相遇是缘，相爱是命。",
      "你是我心灵的支柱。",
      "明天，后天，我都想和你在一起。",
      "有些爱，不需要言语也能传达。",
      "我想一辈子牵着你的手。",
      "你的笑容是我力量的源泉。",
      "无论什么困难，只要我们在一起就能克服。",
      "你的存在就是我的骄傲。",
      "我爱你。除此之外，找不到更好的词。",
      "和你度过的时光是我一生的财富。",
      "送给世界上独一无二、最珍贵的你。",
      "你的幸福就是我的幸福。",
      "谢谢你，我爱你。",
      "我会给你永恒不变的爱。",
      "看着你的侧脸，我就感到无比满足。",
      "你对我来说就像天使一样。",
      "我这辈子都不会放开你。",
      "感谢相遇的奇迹。",
      "在你的眼中，我看到了我们的未来。",
      "爱需要经营，让我们共同珍惜。",
      "只要有你，一切都足够了。",
      "请永远做我的恋人。",
      "用爱的力量照亮世界。",
      "你的温暖包围着我。",
      "你就像我的太阳一样。",
      "我们共同谱写的爱情故事。",
      "爱你，是我一生的使命。",
      "永远，只爱你一人。",
      "愿与你共度余生，看尽世间繁华。",
      "你是我生命中最温柔的底色。",
      "只要有你，哪里都是家。",
      "我会一直守护你，直到地老天荒。",
      "你是我心中永不凋零的花朵。",
      "遇见你之后，我才懂得什么是真正的幸福。",
      "我想把世界上最好的东西都给你。",
      "你的眼睛里，藏着我最向往的未来。",
      "无论未来的路有多难，我们都一起走。",
      "你是我的唯一，也是我的全部。",
      "你的每一句话，都温暖着我的心房。",
      "愿我们的爱情，如细水长流般永恒。",
      "只要牵着你的手，我就有勇气面对一切。",
      "你是我这一生中最美的意外。",
      "我想陪你一起变老，白首不相离。",
      "你的温柔，是我治愈一切的良药。",
      "感谢你走进我的生命，让一切变得有意义。",
      "你是我心中永远的牵挂。",
      "我们的爱，会像繁星一样璀璨。",
      "我爱你，一生一世不分离。",
    ],
    'ru': [
      "Любить — это не значит смотреть друг на друга, любить — значит смотреть вместе в одном направлении.",
      "Твоя улыбка прекраснее всех звезд.",
      "Встреча с тобой — лучшее, что случалось в моей жизни.",
      "Я хочу навсегда остаться рядом с тобой.",
      "Ты — самое дорогое, что у меня есть в этом мире.",
      "Благодаря тебе каждый мой день сияет.",
      "Я люблю тебя больше, чем могут выразить слова.",
      "Ты — моя судьба.",
      "Я счастлив просто быть рядом с тобой.",
      "Пожалуйста, будь со мной всегда.",
      "Ты — мое сокровище.",
      "Что бы ни случилось, я всегда буду защищать тебя.",
      "Твой голос успокаивает мою душу.",
      "С того дня, как я встретил тебя, мой мир изменился.",
      "Каждый миг с тобой — драгоценное воспоминание.",
      "Любовь — это желать счастья другому.",
      "Когда ты улыбаешься, я тоже счастлив.",
      "Спасибо за твою нежность и доброту.",
      "Я так рад, что нашел тебя в этом огромном мире.",
      "Давай идти в будущее вместе.",
      "Я люблю тебя больше всех на свете.",
      "Я люблю в тебе всё.",
      "Встреча — это случайность, любовь — это неизбежность.",
      "Ты — моя опора и поддержка.",
      "Я хочу быть с тобой и завтра, и всегда.",
      "Есть любовь, которую не нужно объяснять словами.",
      "Я никогда не хочу отпускать твою руку.",
      "Твоя улыбка — источник моей силы.",
      "Вместе мы преодолеем любые трудности.",
      "Твое присутствие — моя гордость.",
      "Я люблю тебя. Других слов не нужно.",
      "Время, проведенное с тобой — сокровище всей моей жизни.",
      "Единственной и самой дорогой тебе.",
      "Твое счастье — это моё счастье.",
      "Спасибо тебе за всё. Я люблю тебя.",
      "Я подарю тебе вечную и неизменную любовь.",
      "Просто глядя на тебя, мое сердце наполняется теплом.",
      "Ты для меня — как ангел.",
      "Я никогда тебя не покину.",
      "Я благодарен за чудо нашей встречи.",
      "В твоих глазах я вижу наше будущее.",
      "Любовь нужно беречь. Давай хранить её вместе.",
      "Если ты рядом, мне больше ничего не нужно.",
      "Пожалуйста, будь моей любовью навсегда.",
      "Давай осветим этот мир нашей любовью.",
      "Твое тепло согревает меня.",
      "Ты для меня — как солнце.",
      "Наша история любви, которую мы пишем вдвоем.",
      "Любить тебя — моё призвание.",
      "Навечно я люблю только тебя одну.",
      "Ты — мой смысл жизни и моё самое большое вдохновение.",
      "Я обещаю всегда быть твоей опорой и защитой.",
      "Каждый миг, проведённый с тобой, — это подарок судьбы.",
      "Твоя любовь делает меня сильнее с каждым днём.",
      "Я хочу встретить с тобой каждую старость и каждый рассвет.",
      "Ты — самое прекрасное, что случалось в моей вселенной.",
      "Я люблю тебя всем сердцем, и это навсегда.",
      "Твоя улыбка согревает меня даже в самые холодные дни.",
      "Мы — две половинки одного целого, и я счастлив быть с тобой.",
      "Я ценю каждую секунду нашей совместной жизни.",
      "Ты — мой дом, где бы мы ни находились.",
      "Моя любовь к тебе не знает границ и преград.",
      "Я всегда буду рядом, чтобы поддержать тебя в любую минуту.",
      "Ты делаешь мой мир ярче и добрее.",
      "Я благодарен судьбе за то, что ты есть у меня.",
      "Наша любовь — это самое ценное сокровище в моей жизни.",
      "Я хочу делить с тобой все радости и печали.",
      "Ты — мечта, ставшая реальностью.",
      "Я люблю тебя больше, чем можно выразить словами.",
      "Ты — моё всё, и я никогда тебя не отпущу.",
    ],
  };

  static String getRandomQuote(String langCode) {
    final quotes = _allQuotes[langCode] ?? _allQuotes['en']!;
    return quotes[Random().nextInt(quotes.length)];
  }
}
